#ifndef TINYMT32_HOST_H
#define TINYMT32_HOST_H

#include <stdint.h>

/**
 * TinyMT structure
 * mat1, mat2, tmat must be set from tinymt32dc output before initialize
 */
typedef struct TINYMT32_STATUS_T {
    uint32_t status[4];
    uint32_t mat1;
    uint32_t mat2;
    uint32_t tmat;
} tinymt32_status_t;

/**
 * This function reads parameter from file and puts them in an array.
 * The file should be the output of tinymt32dc.
 *
 * @param filename name of the file generated by tinymt32dc.
 * @param params output array of this function.
 * number of elements of the array is num_params * 3.
 * @param num_param number of parameters
 * @return 0 if normal end.
 */
/*
int tinymt32_set_params(const char * filename,
			uint32_t * params,
			int num_param);
*/

#ifdef __cplusplus
extern "C" {
#endif
    int tinymt32_set_params(const char* filename, uint32_t* params, int num_param);
#ifdef __cplusplus
}
#endif

#endif
