#ifndef LKG_DEFAULTS_H_
#define LKG_DEFAULTS_H_

#define DEFAULT_RESULTS_FILENAME "linkage.out"

const int DEFAULT_MCMC_ITERATIONS = 27000;
const int DEFAULT_BURNIN_ITERATIONS = 3000;
const int DEFAULT_SEQUENTIALIMPUTATION_ITERATIONS = 100;
const int DEFAULT_SCORING_PERIOD = 10;
const int DEFAULT_THREAD_COUNT = 1;
const double DEFAULT_LSAMPLER_PROB = 0.5;


#endif
